# UAE tax-compliant print formats for NextAI.
#
# These Print Format records are created/updated programmatically so they ship
# with the app and stay in sync on every `bench migrate` (via the after_migrate
# hook) or by calling `next_ai.uae_print_formats.install_uae_print_formats`.
#
# The company logo and company details (name, address, TRN, contact) are always
# fetched from the linked Company record at print time, so updating Company
# Settings instantly reflects on every document.

import frappe

MODULE = "Next AI"

# ──────────────────────────────────────────────────────────────────────
# Shared styling
# ──────────────────────────────────────────────────────────────────────
_CSS = """
<style>
  .nx-doc { font-family: "Inter","Helvetica Neue",Arial,sans-serif; color:#1f2933; font-size:11px; }
  .nx-doc * { box-sizing:border-box; }
  .nx-head { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:2px solid #0f766e; padding-bottom:12px; margin-bottom:14px; }
  .nx-logo { max-height:70px; max-width:220px; object-fit:contain; }
  .nx-co { text-align:right; }
  .nx-co .nx-co-name { font-size:17px; font-weight:800; color:#0f766e; }
  .nx-co div { line-height:1.5; }
  .nx-trn { font-weight:700; }
  .nx-title { text-align:center; font-size:18px; font-weight:800; letter-spacing:1px; color:#0f172a; margin:6px 0 14px; }
  .nx-meta-wrap { display:flex; justify-content:space-between; gap:18px; margin-bottom:14px; }
  .nx-box { border:1px solid #e2e8f0; border-radius:8px; padding:10px 12px; width:48%; }
  .nx-box h4 { margin:0 0 6px; font-size:10px; text-transform:uppercase; letter-spacing:.6px; color:#0f766e; }
  .nx-box .nx-party-name { font-weight:700; font-size:12px; }
  .nx-meta-grid { width:48%; }
  .nx-meta-grid table { width:100%; border-collapse:collapse; }
  .nx-meta-grid td { padding:3px 0; }
  .nx-meta-grid td.k { color:#64748b; }
  .nx-meta-grid td.v { text-align:right; font-weight:700; }
  table.nx-items { width:100%; border-collapse:collapse; margin-bottom:14px; }
  table.nx-items th { background:#0f766e; color:#fff; padding:7px 8px; font-size:10px; text-align:left; text-transform:uppercase; letter-spacing:.4px; }
  table.nx-items td { padding:7px 8px; border-bottom:1px solid #eef2f6; vertical-align:top; }
  table.nx-items td.num, table.nx-items th.num { text-align:right; }
  table.nx-items tr:nth-child(even) td { background:#f8fafc; }
  .nx-tot-wrap { display:flex; justify-content:flex-end; }
  .nx-tot { width:300px; }
  .nx-tot table { width:100%; border-collapse:collapse; }
  .nx-tot td { padding:5px 8px; }
  .nx-tot td.k { color:#475569; }
  .nx-tot td.v { text-align:right; font-weight:700; }
  .nx-tot tr.grand td { border-top:2px solid #0f766e; font-size:13px; color:#0f766e; font-weight:800; }
  .nx-words { margin:10px 0; font-size:11px; }
  .nx-words b { color:#0f766e; }
  .nx-terms { border-top:1px solid #e2e8f0; margin-top:14px; padding-top:8px; font-size:10px; color:#64748b; white-space:pre-line; }
  .nx-sign { display:flex; justify-content:space-between; margin-top:40px; }
  .nx-sign div { width:40%; border-top:1px solid #94a3b8; padding-top:5px; text-align:center; font-size:10px; color:#64748b; }
  .nx-foot { text-align:center; font-size:9px; color:#94a3b8; margin-top:18px; }
</style>
"""

# Company header — logo + company details + TRN, all from the Company doc.
_HEADER = """
{%- set company = frappe.get_doc("Company", doc.company) -%}
{%- set caddr = (doc.get("company_address_display") or "") -%}
<div class="nx-head">
  <div>
    {% if company.company_logo %}<img class="nx-logo" src="{{ company.company_logo }}">
    {% else %}<div class="nx-co-name" style="font-size:20px;color:#0f766e;font-weight:800">{{ company.company_name }}</div>{% endif %}
  </div>
  <div class="nx-co">
    <div class="nx-co-name">{{ company.company_name }}</div>
    {% if caddr %}<div>{{ caddr }}</div>{% else %}
      {% if company.country %}<div>{{ company.country }}</div>{% endif %}
    {% endif %}
    {% if company.get("phone_no") %}<div>Tel: {{ company.phone_no }}</div>{% endif %}
    {% if company.get("email") %}<div>{{ company.email }}</div>{% endif %}
    {% if company.get("website") %}<div>{{ company.website }}</div>{% endif %}
    {% if company.tax_id %}<div class="nx-trn">TRN: {{ company.tax_id }}</div>{% endif %}
  </div>
</div>
"""

_FOOTER = """
<div class="nx-foot">This is a computer-generated document. Generated by {{ frappe.get_doc("Company", doc.company).company_name }}.</div>
"""


def _party_box(party_type):
    """Bill-to / supplier block. Uses the document's stored display fields and TRN."""
    if party_type == "customer":
        return """
  <div class="nx-box">
    <h4>Bill To</h4>
    <div class="nx-party-name">{{ doc.get("customer_name") or doc.get("customer") }}</div>
    {% if doc.get("address_display") %}<div>{{ doc.address_display }}</div>{% endif %}
    {% if doc.get("contact_display") %}<div>{{ doc.contact_display }}</div>{% endif %}
    {% if doc.get("tax_id") %}<div class="nx-trn">TRN: {{ doc.tax_id }}</div>{% endif %}
  </div>
"""
    return """
  <div class="nx-box">
    <h4>Supplier</h4>
    <div class="nx-party-name">{{ doc.get("supplier_name") or doc.get("supplier") }}</div>
    {% if doc.get("supplier_address_display") or doc.get("address_display") %}<div>{{ doc.get("supplier_address_display") or doc.get("address_display") }}</div>{% endif %}
    {% if doc.get("contact_display") %}<div>{{ doc.contact_display }}</div>{% endif %}
    {% if doc.get("tax_id") or doc.get("supplier_tax_id") %}<div class="nx-trn">TRN: {{ doc.get("tax_id") or doc.get("supplier_tax_id") }}</div>{% endif %}
  </div>
"""


def _meta_rows(rows):
    """rows: list of (label, jinja_value_expr, optional_condition_expr)."""
    out = []
    for label, expr, cond in rows:
        line = '<tr><td class="k">%s</td><td class="v">{{ %s }}</td></tr>' % (label, expr)
        if cond:
            line = "{%% if %s %%}%s{%% endif %%}" % (cond, line)
        out.append(line)
    return '<div class="nx-meta-grid"><table>%s</table></div>' % "".join(out)


def _items_table(show_tax_columns=True):
    """Line items with optional per-line VAT amount column."""
    tax_th = '<th class="num">VAT</th>' if show_tax_columns else ""
    tax_td = (
        '<td class="num">{{ frappe.utils.fmt_money(row.get("tax_amount") or 0, currency=doc.currency) if row.get("tax_amount") else "—" }}</td>'
        if show_tax_columns else ""
    )
    return """
<table class="nx-items">
  <thead><tr>
    <th style="width:28px">#</th>
    <th>Description</th>
    <th class="num">Qty</th>
    <th>UOM</th>
    <th class="num">Rate</th>
    <th class="num">Amount</th>
    %s
  </tr></thead>
  <tbody>
  {%% for row in doc.items %%}
    <tr>
      <td>{{ loop.index }}</td>
      <td><b>{{ row.get("item_name") or row.get("item_code") }}</b>
        {%% if row.get("description") and row.description != row.get("item_name") %%}<div style="color:#64748b;font-size:10px">{{ row.description | striptags }}</div>{%% endif %%}
      </td>
      <td class="num">{{ row.qty }}</td>
      <td>{{ row.get("uom") or row.get("stock_uom") or "" }}</td>
      <td class="num">{{ frappe.utils.fmt_money(row.get("rate") or 0, currency=doc.currency) }}</td>
      <td class="num">{{ frappe.utils.fmt_money(row.get("amount") or 0, currency=doc.currency) }}</td>
      %s
    </tr>
  {%% endfor %%}
  </tbody>
</table>
""" % (tax_th, tax_td)


def _totals(show_vat=True):
    """Totals block: net, discount, each VAT line, grand total, amount in words."""
    vat_lines = ""
    if show_vat:
        vat_lines = """
    {% for t in doc.get("taxes") or [] %}
      {% if (t.tax_amount or 0) != 0 %}
      <tr><td class="k">{{ t.description }}</td><td class="v">{{ frappe.utils.fmt_money(t.tax_amount, currency=doc.currency) }}</td></tr>
      {% endif %}
    {% endfor %}
"""
    return """
<div class="nx-tot-wrap"><div class="nx-tot"><table>
  <tr><td class="k">Total (Excl. VAT)</td><td class="v">{{ frappe.utils.fmt_money(doc.get("net_total") or doc.get("total") or 0, currency=doc.currency) }}</td></tr>
  {%% if (doc.get("discount_amount") or 0) != 0 %%}<tr><td class="k">Discount</td><td class="v">- {{ frappe.utils.fmt_money(doc.discount_amount, currency=doc.currency) }}</td></tr>{%% endif %%}
  %s
  <tr class="grand"><td class="k">Grand Total</td><td class="v">{{ frappe.utils.fmt_money(doc.get("grand_total") or doc.get("rounded_total") or 0, currency=doc.currency) }}</td></tr>
  {%% if (doc.get("outstanding_amount") or 0) > 0 %%}<tr><td class="k">Outstanding</td><td class="v">{{ frappe.utils.fmt_money(doc.outstanding_amount, currency=doc.currency) }}</td></tr>{%% endif %%}
</table></div></div>
{%% if doc.get("in_words") %%}<div class="nx-words"><b>In words:</b> {{ doc.in_words }}</div>{%% endif %%}
""" % vat_lines


def _terms():
    return """
{% if doc.get("terms") %}<div class="nx-terms"><b>Terms &amp; Conditions</b>\n{{ doc.terms | striptags }}</div>{% endif %}
<div class="nx-sign"><div>Authorised Signatory</div><div>Received By</div></div>
"""


def _txn_format(title, party_type, meta_rows, show_vat=True):
    return (
        _CSS
        + '<div class="nx-doc">'
        + _HEADER
        + ('<div class="nx-title">%s</div>' % title)
        + '<div class="nx-meta-wrap">'
        + _party_box(party_type)
        + _meta_rows(meta_rows)
        + "</div>"
        + _items_table(show_tax_columns=show_vat)
        + _totals(show_vat=show_vat)
        + _terms()
        + _FOOTER
        + "</div>"
    )


# Meta rows per document type ------------------------------------------------
_SI_META = [
    ("Invoice No.", "doc.name", None),
    ("Date", "frappe.utils.formatdate(doc.posting_date)", "doc.get('posting_date')"),
    ("Due Date", "frappe.utils.formatdate(doc.due_date)", "doc.get('due_date')"),
    ("Currency", "doc.currency", "doc.get('currency')"),
    ("PO No.", "doc.po_no", "doc.get('po_no')"),
]
_PI_META = [
    ("Bill No.", "doc.name", None),
    ("Supplier Bill", "doc.bill_no", "doc.get('bill_no')"),
    ("Date", "frappe.utils.formatdate(doc.posting_date)", "doc.get('posting_date')"),
    ("Due Date", "frappe.utils.formatdate(doc.due_date)", "doc.get('due_date')"),
    ("Currency", "doc.currency", "doc.get('currency')"),
]
_PO_META = [
    ("Order No.", "doc.name", None),
    ("Date", "frappe.utils.formatdate(doc.transaction_date)", "doc.get('transaction_date')"),
    ("Required By", "frappe.utils.formatdate(doc.schedule_date)", "doc.get('schedule_date')"),
    ("Currency", "doc.currency", "doc.get('currency')"),
]
_SO_META = [
    ("Order No.", "doc.name", None),
    ("Date", "frappe.utils.formatdate(doc.transaction_date)", "doc.get('transaction_date')"),
    ("Delivery Date", "frappe.utils.formatdate(doc.delivery_date)", "doc.get('delivery_date')"),
    ("Currency", "doc.currency", "doc.get('currency')"),
    ("PO No.", "doc.po_no", "doc.get('po_no')"),
]
_DN_META = [
    ("Note No.", "doc.name", None),
    ("Date", "frappe.utils.formatdate(doc.posting_date)", "doc.get('posting_date')"),
    ("Customer PO", "doc.po_no", "doc.get('po_no')"),
    ("Currency", "doc.currency", "doc.get('currency')"),
]


# ──────────────────────────────────────────────────────────────────────
# Salary Slip — UAE / WPS friendly
# ──────────────────────────────────────────────────────────────────────
_SALARY_HTML = (
    _CSS
    + '<div class="nx-doc">'
    + _HEADER
    + '<div class="nx-title">PAYSLIP</div>'
    + """
{%- set emp = frappe.get_doc("Employee", doc.employee) -%}
{%- set approved_leaves = frappe.get_all("Leave Application",
      filters={"employee": doc.employee, "status": "Approved", "docstatus": 1,
               "from_date": ["<=", doc.end_date], "to_date": [">=", doc.start_date]},
      fields=["leave_type", "from_date", "to_date", "total_leave_days"]) -%}
<div class="nx-meta-wrap">
  <div class="nx-box">
    <h4>Employee</h4>
    <div class="nx-party-name">{{ doc.employee_name }}</div>
    <div>ID: {{ doc.employee }}</div>
    {% if emp.get("designation") %}<div>{{ emp.designation }}</div>{% endif %}
    {% if emp.get("department") %}<div>{{ emp.department }}</div>{% endif %}
    {% if emp.get("date_of_joining") %}<div>Joined: {{ frappe.utils.formatdate(emp.date_of_joining) }}</div>{% endif %}
  </div>
  <div class="nx-meta-grid"><table>
    <tr><td class="k">Slip No.</td><td class="v">{{ doc.name }}</td></tr>
    <tr><td class="k">Pay Period</td><td class="v">{{ frappe.utils.formatdate(doc.start_date) }} – {{ frappe.utils.formatdate(doc.end_date) }}</td></tr>
    {% if doc.get("posting_date") %}<tr><td class="k">Pay Date</td><td class="v">{{ frappe.utils.formatdate(doc.posting_date) }}</td></tr>{% endif %}
    <tr><td class="k">Total Days</td><td class="v">{{ doc.total_working_days }}</td></tr>
    <tr><td class="k">Payment Days</td><td class="v">{{ doc.payment_days }}</td></tr>
  </table></div>
</div>

<!-- Bank & Leave details (bank fetched from Employee master) -->
<div class="nx-meta-wrap">
  <div class="nx-box">
    <h4>Bank Details</h4>
    {% if emp.get("bank_name") %}<div><b>Bank:</b> {{ emp.bank_name }}</div>{% endif %}
    {% if emp.get("bank_ac_no") %}<div><b>Account No:</b> {{ emp.bank_ac_no }}</div>{% endif %}
    {% if emp.get("iban") %}<div><b>IBAN:</b> {{ emp.iban }}</div>{% endif %}
    {% if not emp.get("bank_name") and not emp.get("bank_ac_no") and not emp.get("iban") %}<div style="color:#94a3b8">No bank details on employee record.</div>{% endif %}
    {% if doc.get("mode_of_payment") %}<div><b>Mode:</b> {{ doc.mode_of_payment }}</div>{% endif %}
  </div>
  <div class="nx-box">
    <h4>Leave &amp; Attendance</h4>
    <div><b>Absent Days:</b> {{ doc.get("absent_days") or 0 }}</div>
    <div><b>Leave Without Pay:</b> {{ doc.get("leave_without_pay") or 0 }}</div>
    {% if approved_leaves %}
      <div style="margin-top:4px;color:#0f766e;font-weight:700">Approved leave this period:</div>
      {% for l in approved_leaves %}<div>{{ l.leave_type }} — {{ l.total_leave_days }} day(s) ({{ frappe.utils.formatdate(l.from_date) }})</div>{% endfor %}
    {% else %}
      <div style="color:#94a3b8">No approved leave in this period.</div>
    {% endif %}
  </div>
</div>

<div style="display:flex; gap:14px;">
  <table class="nx-items" style="width:50%">
    <thead><tr><th>Earnings</th><th class="num">Amount</th></tr></thead>
    <tbody>
    {% for e in doc.earnings %}{% if (e.amount or 0) != 0 %}
      <tr><td>{{ e.salary_component }}</td><td class="num">{{ frappe.utils.fmt_money(e.amount, currency=doc.currency) }}</td></tr>
    {% endif %}{% endfor %}
      <tr style="font-weight:800"><td>Gross Pay</td><td class="num">{{ frappe.utils.fmt_money(doc.gross_pay, currency=doc.currency) }}</td></tr>
    </tbody>
  </table>
  <table class="nx-items" style="width:50%">
    <thead><tr><th>Deductions</th><th class="num">Amount</th></tr></thead>
    <tbody>
    {% for d in doc.deductions %}{% if (d.amount or 0) != 0 %}
      <tr><td>{{ d.salary_component }}</td><td class="num">{{ frappe.utils.fmt_money(d.amount, currency=doc.currency) }}</td></tr>
    {% endif %}{% endfor %}
      <tr style="font-weight:800"><td>Total Deductions</td><td class="num">{{ frappe.utils.fmt_money(doc.total_deduction, currency=doc.currency) }}</td></tr>
    </tbody>
  </table>
</div>

<div class="nx-tot-wrap"><div class="nx-tot"><table>
  <tr><td class="k">Gross Pay</td><td class="v">{{ frappe.utils.fmt_money(doc.gross_pay, currency=doc.currency) }}</td></tr>
  <tr><td class="k">Total Deductions</td><td class="v">- {{ frappe.utils.fmt_money(doc.total_deduction, currency=doc.currency) }}</td></tr>
  <tr class="grand"><td class="k">Net Pay</td><td class="v">{{ frappe.utils.fmt_money(doc.net_pay, currency=doc.currency) }}</td></tr>
</table></div></div>
{% if doc.get("total_in_words") %}<div class="nx-words"><b>In words:</b> {{ doc.total_in_words }}</div>{% endif %}
<div class="nx-sign"><div>Employee Signature</div><div>Authorised Signatory</div></div>
"""
    + _FOOTER
    + "</div>"
)


# ──────────────────────────────────────────────────────────────────────
# Registry & installer
# ──────────────────────────────────────────────────────────────────────
def _formats():
    return [
        ("NextAI Tax Invoice", "Sales Invoice", _txn_format("TAX INVOICE", "customer", _SI_META, show_vat=True)),
        ("NextAI Invoice", "Sales Invoice", _txn_format("INVOICE", "customer", _SI_META, show_vat=True)),
        ("NextAI Purchase Invoice", "Purchase Invoice", _txn_format("PURCHASE TAX INVOICE", "supplier", _PI_META, show_vat=True)),
        ("NextAI Purchase Order", "Purchase Order", _txn_format("PURCHASE ORDER", "supplier", _PO_META, show_vat=True)),
        ("NextAI Sales Order", "Sales Order", _txn_format("SALES ORDER", "customer", _SO_META, show_vat=True)),
        ("NextAI Delivery Note", "Delivery Note", _txn_format("DELIVERY NOTE", "customer", _DN_META, show_vat=False)),
        ("NextAI Salary Slip", "Salary Slip", _SALARY_HTML),
    ]


def _upsert(name, doc_type, html):
    values = {
        "doctype": "Print Format",
        "name": name,
        "doc_type": doc_type,
        "module": MODULE,
        "standard": "No",
        "custom_format": 1,
        "print_format_type": "Jinja",
        "html": html,
        "font_size": 11,
        "margin_top": 12,
        "margin_bottom": 12,
        "margin_left": 12,
        "margin_right": 12,
        "disabled": 0,
    }
    if frappe.db.exists("Print Format", name):
        pf = frappe.get_doc("Print Format", name)
        pf.update(values)
        pf.save(ignore_permissions=True)
    else:
        frappe.get_doc(values).insert(ignore_permissions=True)


def install_uae_print_formats():
    """Create or refresh all UAE print formats. Safe to run repeatedly."""
    if not frappe.db.table_exists("Print Format"):
        return
    created = []
    for name, doc_type, html in _formats():
        try:
            _upsert(name, doc_type, html)
            created.append(name)
        except Exception:
            frappe.log_error(frappe.get_traceback(), "NextAI: install print format %s" % name)
    frappe.db.commit()
    return created


@frappe.whitelist()
def setup_uae_print_formats():
    """Whitelisted wrapper so the formats can be (re)installed from the UI/console."""
    frappe.only_for(("System Manager", "Administrator"))
    return install_uae_print_formats()
